# name: running-a-workflow-with-a-matrix
# run-name: workflow run by @${{ github.actor }}
#
# # on:
# #   push:
# on:
#   push:
#     branches:
#       - foobarbaz
#
#   workflow_dispatch:
#
# jobs:
#   create-new-issue:
#     uses: ./.github/workflows/create-failure-issue.yml
#     secrets: inherit
#     permissions:
#       issues: write
#     strategy:
#       matrix:
#         env: [foo, bar]
#         level: [dev, stage, prod]
#     with:
#       title: "${{ matrix.env}} ${{ matrix.level}} issue"
#       body: "Fix this ${{ matrix.env}} ${{ matrix.level}} issue"
#
#   report-issue-number:
#     runs-on: ubuntu-latest
#     needs: create-new-issue
#     steps:
#       - run: |
#           echo ${{ needs.create-new-issue.outputs.INUM }}
#           echo ${{ needs.create-new-issue.outputs.BUILD_STAGE }}

name: running-a-workflow-with-a-matrix
run-name: workflow run by @${{ github.actor }}

on:
  push:
    branches:
      - foobarbaz

  workflow_dispatch:

jobs:
  create-new-issue:
    uses: ./.github/workflows/create-failure-issue.yml
    secrets: inherit
    permissions:
      issues: write
    strategy:
      matrix:
        env: [foo, bar]
        level: [dev, stage, prod]
    with:
      title: "${{ matrix.env }}-${{ matrix.level }}"
      body: "Fix this ${{ matrix.env }} ${{ matrix.level }} issue"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./results

      - name: combine-results
        run: |
          jq -s '.' results/**/result.json > combined.json
          cat combined.json | jq

      - name: show-table
        run: |
          # cat combined.json | jq -r '.[] | "\(.KEY)\t\(.INUM)\t\(.BUILD_STAGE)"'
          cat combined.json | jq -r '.[] | "\(.KEY);;;\(.INUM);;;\(.BUILD_STAGE)"'
