name: Basic Action
run-name: workflow run by @${{ github.actor }}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "main" ]
    branches: [ "foobarbaz" ]
  pull_request:
    branches: [ "foobarbaz" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to use the action locally
        # uses: actions/checkout@v3.5.3
        uses: actions/checkout@v3

      - name: Run my own container action
        id: action
        uses: ./
        with:
          who-to-greet: '@RamonElias'

      - name: Output the answer
        run: echo "The answer is ${{ steps.action.outputs.answer }}"

      - name: Test the container
        if: ${{ steps.action.outputs.answer != 57 }}
        run: |
          echo "::error file=entrypoint.sh,line=5,title=Error in container::The answer was not expected"
          exit 1
